name: scrap_job

on:
  schedule:
    - cron: '0 9 * * *'  # todos los días a las 9:00 AM UTC
  workflow_dispatch:     # permite ejecutarlo manualmente desde la UI

jobs:
  run_scrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          python scrap_job.py
